package com.andersenlab.autotests.site.page.techstack.mobile.ios.blocks;

import com.andersenlab.autotests.site.page.services.customsoftware.blocks.customerreviews.CustomerReviewsData;
import lombok.Getter;

@Getter
public class CustomerReviewsDataIos implements CustomerReviewsData {
    private final String[][] TEXT_ARTICLES = new String[][]{
            {"Christian Johnsson", "CEO at Ventunix Consulting", "", "Andersen delivered the mobile app right to our expectations. Their swift workflow complemented their professional management style. Andersen's team is available to its clients.", ""},
            {"Juba Kamkamidze", "Scrum master at Space Neobank", "", "It is a team of responsible and always motivated super professionals, who successfully addressed complex aspects of our mobile banking software development.", ""},
            {"Neil Kelly", "Engineering Director at Yellow Card", "", "Andersen's engineering team knows our business very well. They create architecture and cover mobile software development. Their skilled expertise supplemented ongoing engagement and partnership. The team at Andersen is communicative and responsive. They act as part of the team, going above & beyond to develop our Cryptocurrency Exchange Platform. Their professionalism is top-notch as well.", ""},
            {"Jonathan Bibas", "CTO at The Data Driven Company", "", "Cooperation with Andersen was a good experience for sure. Our previous vendor never met the deadlines, and since it was crucial for us to receive the software in the shortest possible terms, strict compliance with deadlines was our main requirement for Andersen’s team. And during the whole process of our website and mobile app improvement, punctuality was always respected, despite the fact the team included only 5 specialists.", START_WITH + "/our-projects/software-for-monitoring-vehicle-diagnostic-devices"},
            {"Roxana Porada", "Founder & VP Products at PXL Vision", "", "The best thing about Andersen’s services is the full transparency of processes. We always knew what’s going on with our business app and didn’t need to worry much about this project status, so it gives us the opportunity to focus on our business.", START_WITH + "/our-projects/verifeye"},
            {"John Specter", "Deputy Director at Samsung electronics", "", "There were some difficulties at the start of the project because we had to spend much time on requirements elicitation. But then Andersen suggested us to add a business analyst and the job went well. Finally, I was able to focus on business objectives instead of project control. Andersen showed us how can outsource vendors develop an expensive solution with high quality.", START_WITH + "/our-projects/application-for-smart-tvs"},
            {"Dave Meirick", "Director - Business Strategy and Development at RoadSafe Traffic Systems", "", "We were looking for an experienced development partner to expand our project further and we can't imagine not working with Andersen. Their professionalism, flexibility, and expertise are undeniable. This traffic monitoring app’s design elements and functionalities align with the original requirements. Andersen’s smooth and organized workflow laid grounds for a successful project and lasting partnership.", ""},
            {"Cameron Champion", "Executive Director at Parallel", "", "This life improvement app is very user-friendly, customers and third parties are impressed by how functional and pertinent the platform is. Andersen’s commitment to the project allowed us to consult changes and track the progress on a regular basis. Timely and client-oriented, the team takes ownership of their work.", ""},
            {"Barak Aviv", "QA Manager at Top Image Systems", "", "We hired 5 QA engineers from Andersen for functional mobile testing of the application for image capture and processing. Despite the fact that the app has web and mobile versions and is designed to make mobile check deposits, enrollment, account opening, bill payment, and other mobile-initiated processes simple and fun, Andersen's team successfully coped with such a difficult and creative task. Communication was remarkably good, even with the time zone difference.", ""},
            {"Ethan Kelley", "Product manager", "", "We decided to launch such a service to help people who fight with severe diseases find medical cannabis, as well as nearby dispensaries, vape accessory shops, and doctors easily, with the help of functional and user-friendly web and mobile applications. And we managed to achieve our goal with the help of a software team from Andersen. The developers conducted diligent work to make the services even more convenient.", START_WITH + "/our-projects/app-for-medical-cannabis-search"}
    };
    private final int artsQuantity = TEXT_ARTICLES.length;
    private final Boolean buttonSlick = true;
}
