package com.andersenlab.autotests.core.configs.basetest;

public enum Pages {
    HOMEPAGE, ABOUT_US, CAREERS, OUR_PROJECTS, CORPORATE_SOCIAL_RESPONSIBILITY, PRIVACY_POLICY, PROJECT_CASES,
    PROMOCODES, CORPORATE_LIFE,

    //tech stack
    FRONTEND, ANGULAR, JAVASCRIPT, REACT_JS, VUE_JS,
    BACKEND, JAVA, DOT_NET, PHP, PYTHON, RUBY, NODE_JS, SCALA, GOLANG, C_CPP,
    MOBILE, ANDROID, IOS, XAMARIN, REACT_NATIVE, IONIC, FLUTTER, RUST,

    //industries
    E_COMMERCE, FINANCIAL_SERVICES, E_LEARNING, TRAVEL_AND_HOSPITALITY,
    HEALTHCARE, MEDIA_AND_ENTERTAINMENT, REAL_ESTATE, TELECOM,
    CUSTOM_IGAMING_SOFTWARE_DEVELOPMENT, LOGISTICS, ENTERPRISE, RETAIL, AUTOMOTIVE,

    //industries subpage
    BETTING, IGAMING_PLATFORM_DEVELOPMENT, PLATFORM_DEVELOPMENT,
    EMR_SOLUTIONS, DATA_ANALYTICS_AND_IOMT, CUSTOM_MEDICAL_SOFTWARE, TELEHEATH_SOLUTIONS, FINANCIAL_SERVICES_BANKING,
    FINANCIAL_SERVICES_FINTECH, FINANCIAL_SERVICES_INVESTMENT, FINANCIAL_SERVICES_INSURANCE,
    MEDICAL_PRACTICE_MANAGEMENT_SOFTWARE, HEALTHCARE_SOFTWARE_DEVELOPERS, REVENUE_CYCLE_MANAGEMENT_SOFTWARE,
    REMOTE_PATIENT_MONITORING_SOFTWARE, PACS_DICOM_SOFTWARE, HEALTH_INFORMATION_MANAGEMENT_SOFTWARE, HEALTHCARE_AI_SOFTWARE_SOLUTIONS,
    CUSTOM_ASSISTIVE_TECHNOLOGY_SOFTWARE_SOLUTIONS, MOBILE_HEALTHCARE_APPLICATIONS, MENTAL_HEALTH_DIGITAL_SOLUTIONS,
    HEALTH_INFORMATION_EXCHANGE_SOFTWARE, HEALTH_INFORMATION_SECURITY_AND_COMPLIANCE, HOSPITAL_MANAGEMENT_SOFTWARE,
    ORDER_MANAGEMENT_SOFTWARE_DEVELOPMENT, TRANSPORTATION_MANAGEMENT_SOFTWARE_DEVELOPMENT, WAREHOUSE_MANAGEMENT_SOFTWARE_DEVELOPMENT,
    INVENTORY_MANAGEMENT_SOFTWARE_DEVELOPMENT, BANKING_BIGDATA_SOLUTIONS, BANKING_DIGITAL_TRANSFORMATION,
    BANKING_INTEGRATION_SOFTWARE, CORE_BANKING_SOFTWARE_SOLUTIONS, CUSTOM_LOAN_SOFTWARE_SOLUTIONS,
    DIGITAL_BANKING_SOFTWARE_DEVELOPMENT, CUSTOM_BLOCKCHAIN_SOFTWARE_DEVELOPMENT, ALTERNATIVE_LENDING_SOFTWARE,
    CLOUD_FINTECH_SOLUTIONS, CRYPTO_CURRENCY_DEVELOPMENT_SERVICES, CUSTOM_DIGITAL_WALLET_DEVELOPMENT, FINTECH_PAYMENT_SOLUTIONS,
    PERSONAL_FINANCE_SOLUTIONS, ASSET_MANAGEMENT_SOFTWARE, CUSTOM_TRADING_SOFTWARE, FINANCIAL_ANALYSIS_SOFTWARE,
    INVESTMENT_COMPLIANCE_DEVELOPMENT, MOBILE_INVESTMENT_SOFTWARE, TRADING_API_DEVELOPMENT, IGAMING_PLATFORM_SECURITY,
    PRODUCTION_OPERATIONS_SUPPORT, INTEGRATIONS, MULTI_DEVICES_BROWSERS_SUPPORT, UIUX_GAMEART_DESIGN,
    CUSTOM_EHR_DEVELOPMENT, EHR_CUSTOMIZATION, EHR_INTEGRATION, DANIEL_KRAFTON_HEALTH_TECHS_FUTURE,

    //services
    CUSTOM_SOFTWARE, MOBILE_DEV, SALES_FORCE, QA, BA, MAINTENANCE, TEAM_AUGMENTATION, UIUX_DESIGN, WEB_DEVELOPMENT_SERVICES,
    PRODUCT_DEVELOPMENT_SERVICES, DEVOPS_SERVICES, SOLUTION_ARCHITECTURE_SERVICES, CLOUD_DEVELOPMENT_SERVICES, IT_SECURITY_SERVICES,
    DISCOVERY_PHASE_FOR_SOFTWARE_PROJECT, AGILE_IT_PROJECT_MANAGEMENT, DATA_SCIENCE, DISCOVERY_PHASE, OUTSOURCED_IT_SERVICES,

    //services subpage
    UIUX_DESIGN_AUDIT, PRODUCT_DESIGN_SERVICES, MOBILE_DESIGN, WEB_DESIGN, BRANDING_DESIGN, GRAPHIC_DESIGN, OUTSOURCED_CALL_CENTER,
    ADVANCED_IT_SUPPORT_SERVICES, INFRASTRUCTURE_AND_DEVELOPMENT_SUPPORT, AMAZON_WEB_SERVICES, AUTOMATION_TESTING_SERVICES,
    MANAGED_TESTING_SERVICES, CUSTOM_TESTING_SERVICES, ADVANCED_CUSTOMER_SUPPORT, IT_EXPENSE_OPTIMIZATION, IT_SERVICE_REPORTS,
    ADVANCED_TECHNICAL_SUPPORT_FOR_USERS, ANDERSEN_QA_COMMUNITY, QA_AUDIT_SERVICES,

    //company
    BLOG, TESTIMONIALS,

    //other
    MEET_US_TOMORROW, PRICING, PROJECT_MAP
}
