package com.andersenlab.autotests.site.page.services.customsoftware.blocks.customerreviews;

import lombok.Getter;

@Getter
public class CustomerReviewsDataCustomSoftware implements CustomerReviewsData {
    private final String[][] TEXT_ARTICLES = new String[][]{
            {"", "Technical Lead at TUI Deutschland", "", "The Front-End development team provided helped us push out high-quality products in a timely manner, meeting our expectations, so we could fully focus on our clients. Andersen's hard-working and talented people establish open and honest communication to ensure a smooth workflow.", ""},
            {"", "Product Owner at FTI", "", "Andersen satisfied the requirements by designing our outsourcing services and adhering to the budget and schedule. They helped us define project goals and provided some actionable insights. The team handled project management seamlessly and worked quickly to deliver the final product in just a few months.", ""},
            {"Jouni Stam", "CTO at Yonoton", "", "The company made a great first impression with the business analyst who gathered requirements, measured the scope, and asked about our other needs. The project manager and other team members kept us informed about the business app's schedule and progress and made sure that everything was going according to our expectations. Andersen stands out where it comes to communication and planning.", START_WITH + "/our-projects/app-for-ordering-tickets-and-meal-during-matches"},
            {"Jeffrey Reyes", "Head of Testing at 3D4Medical Limited", "", "We have just started our relationship with Andersen, and they have proven to be a professional and effective organization. To date, my needs have been in the area of our healthcare consulting app's Quality Assurance. Projects were organized quickly, delivered successfully, and to a high standard. Working with a remote contractor, communication is key, and this Andersen excels in. I would highly recommend Andersen as a supplier of a quality product that meets specifications and is always ready on time.", ""},
            {"Heloïse Pinette", "Public relations expert at BNP Paribas", "", "Experts from Andersen showed incredible dedication and creativity while helping us meet this challenge. We discussed what was expected from the product with Business Analysts, and the result didn’t disappoint us: the solution includes all the necessary modules and functionality to cope with banking regulatory documents analysis effectively.", START_WITH + "/our-projects/solution-for-legislation-changes-monitoring"},
            {"Maxim Ezerskiy", "Vice-president at GMCS", "", "I didn’t believe that a domestic outsourcing vendor could create a qualitative bug-free software product, but the work performed by Andersen’s developers and their dedication made me change my mind. The Point-of-Sale software delivered by Andersen works smoothly and error-free, allowing me and my employees to relax and rely entirely on it.", START_WITH + "/our-projects/software-for-pos-terminal"},
            {"Vasili Shamshur", "Senior Manager at IHS Markit", "", "Andersen has done an outstanding job to complete the project on time. The multitude of issues that the analytical system and management platform development throw at them has been handled professionally and efficiently. We definitely enjoy cooperation with this company and will continue to work with it in the future.", START_WITH + "/our-projects/software-platforms-for-engineers"},
            {"Yury Galustov", "Regional Director at IG Soft", "", "To begin with, I would like to mention that Andersen makes the development process absolutely clear. We were able to interview the React team provided and check their skills. They worked according to best practices accepted in our company, communication was comfortable for both sides, and we obtained full information about our payment app development. It was a pleasure doing business with you.", ""},
            {"Antti Paukku", "Software Architect at Mangement Events", "", "Throughout the duration of the project, from requirements gathering to implementation, the Front-End engineers of Andersen have conducted themselves with the utmost professionalism and dedication to the process transformation project. The people at Andersen fulfilled their obligations taking into account our best interests. Their sincere interest in wanting to help us achieve our goals was readily apparent throughout the development process.", START_WITH + "/our-projects/system-for-managing-events"},
            {"Christian Johnsson", "CEO at Ventunix Consulting", "", "Andersen delivered the mobile app right to our expectations. Their swift workflow complemented their professional management style. Andersen's team is available to its clients.", ""}
    };
    private final int artsQuantity = TEXT_ARTICLES.length;
    private final Boolean buttonSlick = false;
}