package com.andersenlab.autotests.site.page.services.augmentation.testimonials;

import com.andersenlab.autotests.site.page.services.customsoftware.blocks.customerreviews.CustomerReviewsData;
import lombok.Getter;

@Getter
public class CustomerRewiewsData implements CustomerReviewsData {
    private final String[][] TEXT_ARTICLES = new String[][]{
            {"Janis Staseluns", "Group Head of IT Service Management", "https://clutch.co/profile/andersen?page=3&sort_by=date_ACS#review-1331679", "Andersen, having huge experience in lending solutions, provides a cross-functional team that created the solution needed from scratch and customized it for use in more than 11 different regions. Andersen is quick to respond to business requests, and they have a deep talent bench to pull from. Customers can expect a professional and timely partner.", START_WITH + "/our-projects/system-for-issuing-short-term-loans"},
            {"Christian A. Mathiesen", "Head of Research and Development at Purity IT AS", "", "Our partnership with Andersen started 3 years ago, and for all this time the company neither failed us during the reporting and administration system development process nor made us doubt our choice of outsourcing vendor. We are quite satisfied with our cooperation and going to extend the development team.", START_WITH + "/our-projects/reporting-and-administration-software"},
            {"Heloïse Pinette", "Public relations expert at BNP Paribas", "", "Experts from Andersen showed incredible dedication and creativity while helping us meet this challenge. We discussed what was expected from the product with Business Analysts, and the result didn’t disappoint us: the solution includes all the necessary modules and functionality to cope with banking regulatory documents analysis effectively.", START_WITH + "/our-projects/solution-for-legislation-changes-monitoring"},
            {"Vladimir Kovalenko", "Head of software development at Tinkoff Insurance", "https://clutch.co/profile/andersen?page=7&sort_by=date_ACS#review-1616411", "We have been working with Andersen for more than 4.5 years. They provide us with scrum teams and consulting services. Working together, we have created hundreds of new features and improvements for the banking software. They helped us to establish a very efficient quality assurance process, as well as to move forward in the field of quality control automation. We are completely satisfied with our cooperation and can definitely recommend Andersen as a reliable partner.", START_WITH + "/our-projects/solution-for-a-virtual-bank"},
            {"Maxim Ezerskiy", "Vice-president at GMCS", "https://clutch.co/profile/andersen?page=1&sort_by=date_ACS#review-1176602", "I didn’t believe that a domestic outsourcing vendor could create a qualitative bug-free software product, but the work performed by Andersen’s developers and their dedication made me change my mind. The Point-of-Sale software delivered by Andersen works smoothly and error-free, allowing me and my employees to relax and rely entirely on it.", START_WITH + "/our-projects/software-for-pos-terminal"},
            {"Vasili Shamshur", "Senior Manager at IHS Markit", "https://clutch.co/profile/andersen?sort_by=date_ACS#review-218613", "Andersen has done an outstanding job to complete the project on time. The multitude of issues that the analytical system and management platform development throw at them has been handled professionally and efficiently. We definitely enjoy cooperation with this company and will continue to work with it in the future.", START_WITH + "/our-projects/software-platforms-for-engineers"},
            {"Gert Becker", "PR Manager", "https://clutch.co/profile/andersen?page=2&sort_by=date_ACS#review-1288679", "Establishing this partnership, we planned to give Andersen a try and pass them the development of one subproject to see their performance. The work was done well enough, so we gave these guys another task. And thus, step by step, Andersen’s engineers won our confidence with their clean code, business-friendly ideas, and full transparency. Our cooperation extended to the work on four subprojects in the travel industry, and we are ready to entrust them with a task of any complexity.", START_WITH + "/our-projects/solutions-for-travel-services"},
            {"Yuriy Kartsev", "Mobile Dev Lead at Alfa Capital", "https://clutch.co/profile/andersen#review-1198314", "Both internal and external stakeholders are pleased with the new chat feature in our mobile app. Regular communication and rapid problem resolutions were hallmarks of the engagement. Andersen's development expertise sets it apart from other providers.", ""},
            {"Gleb Smorodkin", "CTO", "https://clutch.co/profile/andersen?page=4&sort_by=date_ACS#review-1383347", "I want to express my gratitude to Andersen company and each member of the team we were lucky enough to work with. I should note not only their excellent technical skills but also very good competencies in the payments and cards area. We are glad to have Andersen as a partner and hope our cooperation will be strengthened each day.", START_WITH + "/our-projects/solution-for-internet-acquiring"},
            {"Antti Paukku", "Software Architect at Management Events", "", "Throughout the duration of the project, from requirements gathering to implementation, the Front-End engineers of Andersen have conducted themselves with the utmost professionalism and dedication to the process transformation project. The people at Andersen fulfilled their obligations taking into account our best interests. Their sincere interest in wanting to help us achieve our goals was readily apparent throughout the development process.", START_WITH + "/our-projects/system-for-managing-events"}
    };
    private final int artsQuantity = TEXT_ARTICLES.length;
    private final Boolean buttonSlick = true;
}
