package com.andersenlab.autotests.site.page.techstack.backend.nodejs.blocks;

import com.andersenlab.autotests.site.page.services.customsoftware.blocks.customerreviews.CustomerReviewsData;
import lombok.Getter;

@Getter
public class CustomerReviewsDataNodeJS implements CustomerReviewsData {
    private final String[][] TEXT_ARTICLES = new String[][]{
            {"Vladimir Kovalenko", "Head of software development at Tinkoff Insurance", "", "We have been working with Andersen for more than 4.5 years. They provide us with scrum teams and consulting services. Working together, we have created hundreds of new features and improvements for the banking software. They helped us to establish a very efficient quality assurance process, as well as to move forward in the field of quality control automation. We are completely satisfied with our cooperation and can definitely recommend Andersen as a reliable partner.", START_WITH + "/our-projects/solution-for-a-virtual-bank"},
            {"Sören Andersson", "Scrum Master at Yonoton", "", "Our ordering platform development was successful, resulting in quick growth for the company. Andersen provides quality results on time, adhering to set deadlines. The team is hard-working, dedicated, and professional.", ""},
            {"Yury Galustov", "Regional Director at IG Soft", "", "To begin with, I would like to mention that Andersen makes the development process absolutely clear. We were able to interview the React team provided and check their skills. They worked according to best practices accepted in our company, communication was comfortable for both sides, and we obtained full information about our payment app development. It was a pleasure doing business with you.", ""},
            {"Jouni Stam", "CTO at Yonoton", "", "The company made a great first impression with the business analyst who gathered requirements, measured the scope, and asked about our other needs. The project manager and other team members kept us informed about the business app's schedule and progress and made sure that everything was going according to our expectations. Andersen stands out where it comes to communication and planning.", START_WITH + "/our-projects/app-for-ordering-tickets-and-meal-during-matches"},
            {"Jessica Bourne", "Chief of Staff Team at AT&T", "", "Developers from Andersen are brilliant in their expertise. Great communication skills, reporting various challenges ahead of time. Andersen’s commitment to our information system development project allowed us to consult changes and track the progress on a regular basis. Given the complexity of the project, we're very happy with their output thus far.", ""},
            {"Dalia Burack", "Vice President at Bluegreen Vacations", "", "Resources Andersen provided were capable, reliable, and committed. They demonstrated best-in-class communication to offset challenges inherent to remote collaboration. They understood project goals well and did great at developing a functional back-end for data storage and analysis. The team performed very thorough testing, which has resulted in good customer satisfaction rates.", ""},
            {"Heikki Räisänen", "CEO at Emfit", "", "We are completely satisfied with Andersen as a partner. We are happy with the effective and innovative interface that Andersen has developed for our healthcare app. Thank you and hope our further cooperation will remain fruitful.", START_WITH + "/our-projects/iot-solution-for-monitoring-sleep-quality"},
            {"Åsgeir Helland", "CEO and Co-founder at Tooler", "", "Some time ago we worked with Andersen on the development of our rental store website, and since the results were quite satisfactory, we applied to this company again to develop the admin part. We like the way Andersen’s specialists work and the importance they give to the requirements. If we need some other software solution in the future, we will contact this company.", START_WITH + "/our-projects/admin-part-of-the-online-rental-store"},
            {"Kristian Karimo", "President of OurCnC", "", "We have been cooperating with Andersen for more than 3 years. I'm convinced that Andersen's specialists are trustworthy and skillful. They have designed a management panel and a mobile application for our company. Every comment from us was taken into account to create a design that looks perfect and fits all our needs. During the project, we involve UI/UX specialists from Andersen to create our website design as well. I admire the hard-working team that helps me to improve the product. Hope for maintaining our successful collaboration! Thanks a lot!", ""},
            {"Robert Flynn", "Product owner Ericcson", "", "We set the goal of solving the problem with low water quality, and since the problem is serious, we needed the most skilled and motivated developers that would be able to provide a really good code. That’s why it was decided to include Andersen’s Back-End engineers in our large team. We believe that together we will be one step closer to clean water provision.", START_WITH + "/our-projects/iot-solution-for-water-quality-monitoring"}
    };
    private final int artsQuantity = TEXT_ARTICLES.length;
    private final Boolean buttonSlick = true;
}
