package com.andersenlab.autotests.site.page.industries.retail;

import com.andersenlab.autotests.site.page.services.customsoftware.blocks.customerreviews.CustomerReviewsData;
import lombok.Getter;

@Getter
public class CustomerReviewsDataRetail implements CustomerReviewsData {
    private final String[][] TEXT_ARTICLES = new String[][]{
            {"Jouni Stam", "CTO at Yonoton", "", "The company made a great first impression with the business analyst who gathered requirements, measured the scope, and asked about our other needs. The project manager and other team members kept us informed about the business app's schedule and progress and made sure that everything was going according to our expectations. Andersen stands out where it comes to communication and planning.", START_WITH + "/our-projects/app-for-ordering-tickets-and-meal-during-matches"},
            {"Doug McDaniel", "Senior Facilities Manager at Walmart", "", "So far, Andersen has proven that they’re the perfect partner and have built a workforce management platform per requirements. The team was communicative, dedicated, and responsive. Consistent updates, prompt bug fixing, and their emphasis on taking care of their customers make Andersen a top-notch vendor.", ""},
            {"Bonnie Steinlein", "Director Of Information Technology at Costco Wholesale", "", "Andersen's efforts to our marketing analysis platform development successfully decreased spending and increased data collection. They are personable specialists with a tendency to exceed expectations. Their depth of knowledge has been a highlight. We highly recommend Andersen.", ""},
            {"Gaj Varma", "Communication manager at Frugl", "", "We’ve been fortunate to work with Andersen on our money-saving application. We saw their professionalism, communicative and technical skills, which make the entire team personable and enjoyable to work with. Thank you for your diligent work and the responsibility you showed during the project development.", START_WITH + "/our-projects/app-for-groceries-price-comparison"},
            {"Giedrius Šteimantas", "Partner", "", "The added value that Andersen provided during the design and development of the project, including requirement elicitation, coding, testing stages, as well as control over the progress, contributed to the successful completion of this customer experience improving project. We are completely satisfied with our fruitful cooperation with Andersen’s team.", START_WITH + "/our-projects/application-for-real-estate-search"},
            {"Hilda Randall", "Business relationship manager", "", "Andersen was a great business partner to work with. Its team provided expert advice on all phases of our analytical app development, were extremely supportive and responsive to all the queries, and delivered a high-quality market product.", START_WITH + "/our-projects/application-for-marketing-analytics"},
            {"Donald Neal", "Public relations manager", "", "We are lucky to be partners with Andersen’s development team, and we are grateful for their contribution to the flourishing of our startup. We were nervous at first, but Andersen didn’t give us any reason for disappointment. We are completely satisfied with the resulting digital platform and hope for further fruitful cooperation with them.", START_WITH + "/our-projects/digital-platform-for-real-time-voting"},
            {"Peter Stan", "Delivery manager at USU", "", "We hired three PHP engineers to our platform development team, and so far, we are satisfied with the results of their work. For all the time of cooperation, Andersen’s developers delivered clean code, an effective bulk page creation module, and truly valuable APIs we are verily proud of. So I would say that Andersen proved to be a reliable outsourcing vendor with high-skilled staff.", START_WITH + "/our-projects/commercial-property-rent-portal"},
            {"Allison Stewart", "Product manager Advertima", "", "The Andersen team members are very knowledgeable and are ready to design and execute exactly what you envision. Working with Andersen on our AI using software project, we were really satisfied with their professionalism, accurate scheduling, and timely communication. When issues arose, the team stayed on top of the matter until they were successfully resolved.", START_WITH + "/our-projects/application-for-customer-behavior-analysis"},
            {"Jacqueline Moore", "Business relationship manager", "", "Andersen did a great job and helped us a lot with the deep integration of our offline stores into our Salesforce CRM. Good work, team!", ""}
    };
    private final int artsQuantity = TEXT_ARTICLES.length;
    private final Boolean buttonSlick = true;
}
