package com.andersenlab.autotests.site.page.techstack.mobile.mobile.blocks;

import com.andersenlab.autotests.site.page.services.customsoftware.blocks.customerreviews.CustomerReviewsData;
import lombok.Getter;

@Getter
public class CustomerReviewsDataMobile implements CustomerReviewsData {
    private final String[][] TEXT_ARTICLES = new String[][]{
            {"Vladimir Kovalenko", "Head of software development at Tinkoff Insurance", "", "We have been working with Andersen for more than 4.5 years. They provide us with scrum teams and consulting services. Working together, we have created hundreds of new features and improvements for the banking software. They helped us to establish a very efficient quality assurance process, as well as to move forward in the field of quality control automation. We are completely satisfied with our cooperation and can definitely recommend Andersen as a reliable partner.", START_WITH + "/our-projects/solution-for-a-virtual-bank"},
            {"Yuriy Kartsev", "Mobile Dev Lead at Alfa Capital", "", "Both internal and external stakeholders are pleased with the new chat feature in our mobile app. Regular communication and rapid problem resolutions were hallmarks of the engagement. Andersen's development expertise sets it apart from other providers.", ""},
            {"Christian Johnsson", "CEO at Ventunix Consulting", "", "Andersen delivered the mobile app right to our expectations. Their swift workflow complemented their professional management style. Andersen's team is available to its clients.", ""},
            {"Sergey Korenev", "Head designer of internet projects at National Cable Networks", "", "We needed a mobile solution for inner use that would work with both Android and iOS. As we didn’t have such specialists in our company, we decided to outsource the cross-platform development to Andersen. Their specialists created an amazing app that our customers love, and we are pleased with the results too. I would say that your cross-platform developers made a miracle, as it has helped us to double our working efficiency. So many many thanks to you.", ""},
            {"Jouni Stam", "CTO at Yonoton", "", "The company made a great first impression with the business analyst who gathered requirements, measured the scope, and asked about our other needs. The project manager and other team members kept us informed about the business app's schedule and progress and made sure that everything was going according to our expectations. Andersen stands out where it comes to communication and planning.", START_WITH + "/our-projects/app-for-ordering-tickets-and-meal-during-matches"},
            {"Doug McDaniel", "Senior Facilities Manager at Walmart", "", "So far, Andersen has proven that they’re the perfect partner and have built a workforce management platform per requirements. The team was communicative, dedicated, and responsive. Consistent updates, prompt bug fixing, and their emphasis on taking care of their customers make Andersen a top-notch vendor.", ""},
            {"Bonnie Steinlein", "Director Of Information Technology at Costco Wholesale", "", "Andersen's efforts to our marketing analysis platform development successfully decreased spending and increased data collection. They are personable specialists with a tendency to exceed expectations. Their depth of knowledge has been a highlight. We highly recommend Andersen.", ""},
            {"Juba Kamkamidze", "Scrum master at Space Neobank", "", "It is a team of responsible and always motivated super professionals, who successfully addressed complex aspects of our mobile banking software development.", ""},
            {"Peter Ollikainen", "Chairman at Centa Solutions", "", "Our business relations with Andersen started only a few months ago, but I already see that their engineers are really masters of their craft, especially developers of Xamarin for our mobile application. So far, the results are satisfactory: the interface is user-friendly, intuitive, and works the way we need, plus the new portion of functionality is delivered quite fast. We are glad to cooperate with them.", ""},
            {"Kristian Karimo", "President of OurCnC", "", "We have been cooperating with Andersen for more than 3 years. I'm convinced that Andersen's specialists are trustworthy and skillful. They have designed a management panel and a mobile application for our company. Every comment from us was taken into account to create a design that looks perfect and fits all our needs. During the project, we involve UI/UX specialists from Andersen to create our website design as well. I admire the hard-working team that helps me to improve the product. Hope for maintaining our successful collaboration! Thanks a lot!", ""}
    };
    private final int artsQuantity = TEXT_ARTICLES.length;
    private final Boolean buttonSlick = true;
}
