package com.andersenlab.autotests.site.page.services.maintenance.blocks;

import com.andersenlab.autotests.site.page.services.customsoftware.blocks.customerreviews.CustomerReviewsData;
import lombok.Getter;

@Getter
public class CustomerReviewsDataMaintenance implements CustomerReviewsData {
    private final String[][] TEXT_ARTICLES = new String[][]{
            {"Peter Zielke", "CEO at Exigo", "", "As with any solution delivery and operations support project, unforeseen problems arise that have to be addressed. The manner in which the Andersen team rectified even the smallest issue is indeed a tribute to your organization. In addition, we really appreciate an opportunity to be agile in terms of changing needs, because your company was able to provide highly professional engineers able to address new challenges.", START_WITH + "/our-projects/platform-for-direct-sales-companies"},
            {"Alex Davenport", "CEO", "", "Andersen did a great job by establishing a Call Center we need to support our multimedia startup and improving its processes according to our requirements. It allowed us to concentrate the maximum of our resources on the development process without wasting time on services support.", ""},
            {"Jane Mitchell", "Product manager", "", "As our product came to the CIS market we faced the need to support our new customers from that area. We decided to work with Andersen and fully delegated them our support function for the CIS-based customers. Their specialists provided us the level of support services that we needed, so we’re happy with the customer satisfaction level and regular service improvements we see.", ""},
            {"Gennadiy Andreev", "Communications manager", "", "We needed to extend our IT HelpDesk Team to support rapid business growth and we decided to try outsourcing services for such cases. Andersen helped us to extend our existing IT team in the shortest terms without any visible service disruption. The analysis shows that we spent less than initially planned and got a pretty high level of service at the same time, so we’re going to continue our cooperation with Andersen.", ""},
            {"Maksim Shulman", "CEO", "", "I am happy with the cooperation with Andersen which resulted in a much more professional level of IT services than the ones we had before. We’ve delegated Andersen all scope of IT support for our startup team that we need to develop our product. Our team is distributed and located in different parts of the world and that requires a 24/7 schedule, flexible approach, and understanding of different cultures. But Andersen's processes and quality of work are good enough to deal with those requirements and we even got some valuable outcomes we didn’t expect like the recommendations for the improvement of our internal processes. I recommend Andersen as a valuable and trusted vendor of outsourcing IT services.", ""},
            {"Lee Cheng", "Director of services", "", "One of our partners recommended Andersen as a good customer support partner so once we faced the necessity to get some technical support we decided to contact them first. The combination of their rates and the value provided within their services look valuable for us and we’re glad they were able to cover all range of technical support required by our customers. The development of our medicine app is still in progress and new features are added regularly but we see that Andersen's team has the skills and attitude to support them as well. We like the cooperation with Andersen and rate them as a trusted partner.", ""},
            {"Neil Cohen", "COO", "", "We selected Andersen as our outsourced IT support partner looking for the cost optimization and improvement of our internal services. During our cooperation, the Andersen team has proven themselves as IT experts who know best practices in the support area and can implement them. With their attitude and continual improvement approach we got even more than expected, so I recommend Andersen as a great IT support outsourcing partner.", ""},
            {"Jean Leroy", "IT Manager", "", "We were looking for an outsourcing partner that will take care of our internal IT Infrastructure and after some research, we have selected Andersen. From the very beginning, the team has shown a high level of professional IT expertise, the ability to listen carefully to client requirements, and good communication skills. They managed and maintained our servers and network equipment in a timely planned manner, performed required backups and load tests, and they also successfully solved a couple of unplanned issues we had. In summary, we’re glad about the quality of work provided by Andersen and plan to continue our cooperation.", ""},
            {"Bartosz Nowak", "Head of Development", "", "We were looking for an outsourcing partner able to make updates to our travel application tool with the highest level of quality. The outcome was very good as well as the cooperation process itself.", ""},
            {"Derek Mitchell", "Senior Manager", "", "We hired Andersen's team of 6 specialists to help us with the post-implementation light development needs we had. They successfully added new functionality to our internal tool according to our requirements and standards. The processes and communication were on a very good level confirming we have made a proper choice.", ""}
    };
    private final int artsQuantity = TEXT_ARTICLES.length;
    private final Boolean buttonSlick = true;
}
