package com.andersenlab.autotests.site.page.techstack.mobile.android.blocks;

import com.andersenlab.autotests.site.page.services.customsoftware.blocks.customerreviews.CustomerReviewsData;
import lombok.Getter;

@Getter
public class CustomerReviewsDataAndroid implements CustomerReviewsData {
    private final String[][] TEXT_ARTICLES = new String[][]{
            {"Christian Johnsson", "CEO at Ventunix Consulting", "", "Andersen delivered the mobile app right to our expectations. Their swift workflow complemented their professional management style. Andersen's team is available to its clients.", ""},
            {"Juba Kamkamidze", "Scrum master at Space Neobank", "", "It is a team of responsible and always motivated super professionals, who successfully addressed complex aspects of our mobile banking software development.", ""},
            {"Peter Ollikainen", "Chairman at Centa Solutions", "", "Our business relations with Andersen started only a few months ago, but I already see that their engineers are really masters of their craft, especially developers of Xamarin for our mobile application. So far, the results are satisfactory: the interface is user-friendly, intuitive, and works the way we need, plus the new portion of functionality is delivered quite fast. We are glad to cooperate with them.", ""},
            {"Neil Kelly", "Engineering Director at Yellow Card", "", "Andersen's engineering team knows our business very well. They create architecture and cover mobile software development. Their skilled expertise supplemented ongoing engagement and partnership. The team at Andersen is communicative and responsive. They act as part of the team, going above & beyond to develop our Cryptocurrency Exchange Platform. Their professionalism is top-notch as well.", ""},
            {"John Specter", "Deputy Director at Samsung electronics", "", "There were some difficulties at the start of the project because we had to spend much time on requirements elicitation. But then Andersen suggested us to add a business analyst and the job went well. Finally, I was able to focus on business objectives instead of project control. Andersen showed us how can outsource vendors develop an expensive solution with high quality.", START_WITH + "/our-projects/application-for-smart-tvs"},
            {"Basil Stepanov", "Chief Technology Officer at Smart Choice Communications", "", "Andersen produced clean code and impressive deliverables cost-efficiently to support a competitive business advantage. All employees speak English very well. The design and development team works on our security platform development very organized and with modern project management methods. As a customer, we had a full overview of our project all the time.", ""},
            {"Cameron Champion", "Executive Director at Parallel", "", "This life improvement app is very user-friendly, customers and third parties are impressed by how functional and pertinent the platform is. Andersen’s commitment to the project allowed us to consult changes and track the progress on a regular basis. Timely and client-oriented, the team takes ownership of their work.", ""},
            {"Barak Aviv", "QA Manager at Top Image Systems", "", "We hired 5 QA engineers from Andersen for functional mobile testing of the application for image capture and processing. Despite the fact that the app has web and mobile versions and is designed to make mobile check deposits, enrollment, account opening, bill payment, and other mobile-initiated processes simple and fun, Andersen's team successfully coped with such a difficult and creative task. Communication was remarkably good, even with the time zone difference.", ""},
            {"Ethan Kelley", "Product manager", "", "We decided to launch such a service to help people who fight with severe diseases find medical cannabis, as well as nearby dispensaries, vape accessory shops, and doctors easily, with the help of functional and user-friendly web and mobile applications. And we managed to achieve our goal with the help of a software team from Andersen. The developers conducted diligent work to make the services even more convenient.", START_WITH + "/our-projects/app-for-medical-cannabis-search"},
            {"Philip Bishop", "Delivery manager", "", "We heard from our business partners that Andersen is a trusted outsourcing vendor that provides truly qualitative software development services. That’s why we decided to contact Andersen when realized that there was an urgent need for our mobile app improvements. And the team provided for our project didn’t disappoint us. So we can confirm that Andersen is a good choice for your software project.", START_WITH + "/our-projects/app-for-making-payments-and-managing-paperwork"}
    };
    private final int artsQuantity = TEXT_ARTICLES.length;
    private final Boolean buttonSlick = true;
}
