package com.andersenlab.autotests.site.page.industries.videoandentertainment.blocks;

import com.andersenlab.autotests.site.page.services.customsoftware.blocks.customerreviews.CustomerReviewsData;
import lombok.Getter;

@Getter
public class CustomerReviewsDataVideoAndEntertainment implements CustomerReviewsData {
    private final String[][] TEXT_ARTICLES = new String[][]{
            {"John Specter", "Deputy Director at Samsung electronics", "", "There were some difficulties at the start of the project because we had to spend much time on requirements elicitation. But then Andersen suggested us to add a business analyst and the job went well. Finally, I was able to focus on business objectives instead of project control. Andersen showed us how can outsource vendors develop an expensive solution with high quality.", START_WITH + "/our-projects/application-for-smart-tvs"},
            {"Julia Pokhodina", "Senior Project Manager at Anima Interactive Agency", "", "We asked Andersen to conduct complex testing of the website we developed. During the communication, Andersen specialists offered us an efficient and cost-effective option that allowed us to save money. From the very beginning of our cooperation, the communication with experts was at a good level, and in the course of testing, Andersen proved their professionalism, providing quality work on time. Thank you!", ""},
            {"Kari Rosenberg", "Director of Development at Marvel", "", "Andersen delivered а requests analysis product that successfully satisfied all user needs. Both the quality and quantity of their work have been substantial. They've fostered a positive partnership based on transparency. Andersen is an attentive, accessible team.", ""},
            {"Dr. Mirko Jaumann", "COO at Doppelgänger", "", "Andersen successfully executed a mobile app for our startup, that serves as the client's core offering. We were always kept well informed of the project progress. Additionally, the team was friendly and easy to work with, their response rate and the quality of code were particularly impressive.", ""},
            {"Maxim Khorev", "Product owner", "", "Having worked with Andersen's team for more than a year, I would say that this is a professional firm that knows its business pretty well. This vendor offers skilled developers that have great ideas, provide innovative solutions, and truly care about doing a good job. Thank you, guys, for everything you have done for our online movie theatre!", START_WITH + "/our-projects/platform-for-watching-videos-on-smart-tvs"},
            {"Roger Lawson", "Product manager", "", "IT guys from Andersen grasp things in a single flash! During our cooperation, we had to change requirements to our secure sharing product hundreds of times, and fortunately, it didn’t cause any trouble, so we received quality software at the end. You are amazing, guys!", START_WITH + "/our-projects/application-for-encrypted-message-communication"},
            {"Henry Robertson", "Product Owner", "", "The partnership with Andersen was a pleasant experience that resulted in fruitful cooperation. During the management software development process, we felt confident in their dedication, tech skills, and commitment to deadlines. Andersen is a partner that will always lend you a shoulder when you need help.", START_WITH + "/our-projects/enterprise-asset-management-software"},
            {"Jean Leroy", "IT Manager", "", "We were looking for an outsourcing partner that will take care of our internal IT Infrastructure and after some research, we have selected Andersen. From the very beginning, the team has shown a high level of professional IT expertise, the ability to listen carefully to client requirements, and good communication skills. They managed and maintained our servers and network equipment in a timely planned manner, performed required backups and load tests, and they also successfully solved a couple of unplanned issues we had. In summary, we’re glad about the quality of work provided by Andersen and plan to continue our cooperation.", ""},
            {"", "Owner", "", "Development, QA, and AQA engineers provided by Andersen have contributed significantly to the development of our platform. The team helped with the implementation of 6 main functions, expanded coverage of QA and AQA, and now holding business conferences and exhibitions online will become even more convenient for our clients.", ""}
    };
    private final int artsQuantity = TEXT_ARTICLES.length;
    private final Boolean buttonSlick = true;
}
