package com.andersenlab.autotests.site.page.techstack.backend.backend.blocks;

import com.andersenlab.autotests.site.page.services.customsoftware.blocks.customerreviews.CustomerReviewsData;
import lombok.Getter;

@Getter
public class CustomerReviewsDataBackEnd implements CustomerReviewsData {
    private final String[][] TEXT_ARTICLES = new String[][]{
            {"Vladimir Kovalenko", "Head of software development at Tinkoff Insurance", "", "We have been working with Andersen for more than 4.5 years. They provide us with scrum teams and consulting services. Working together, we have created hundreds of new features and improvements for the banking software. They helped us to establish a very efficient quality assurance process, as well as to move forward in the field of quality control automation. We are completely satisfied with our cooperation and can definitely recommend Andersen as a reliable partner.", START_WITH + "/our-projects/solution-for-a-virtual-bank"},
            {"Maxim Ezerskiy", "Vice-president at GMCS", "", "I didn’t believe that a domestic outsourcing vendor could create a qualitative bug-free software product, but the work performed by Andersen’s developers and their dedication made me change my mind. The Point-of-Sale software delivered by Andersen works smoothly and error-free, allowing me and my employees to relax and rely entirely on it.", START_WITH + "/our-projects/software-for-pos-terminal"},
            {"Sören Andersson", "Scrum Master at Yonoton", "", "Our ordering platform development was successful, resulting in quick growth for the company. Andersen provides quality results on time, adhering to set deadlines. The team is hard-working, dedicated, and professional.", ""},
            {"Yuriy Kartsev", "Mobile Dev Lead at Alfa Capital", "", "Both internal and external stakeholders are pleased with the new chat feature in our mobile app. Regular communication and rapid problem resolutions were hallmarks of the engagement. Andersen's development expertise sets it apart from other providers.", ""},
            {"Yury Galustov", "Regional Director at IG Soft", "", "To begin with, I would like to mention that Andersen makes the development process absolutely clear. We were able to interview the React team provided and check their skills. They worked according to best practices accepted in our company, communication was comfortable for both sides, and we obtained full information about our payment app development. It was a pleasure doing business with you.", ""},
            {"Sergey Korenev", "Head designer of internet projects at National Cable Networks", "", "We needed a mobile solution for inner use that would work with both Android and iOS. As we didn’t have such specialists in our company, we decided to outsource the cross-platform development to Andersen. Their specialists created an amazing app that our customers love, and we are pleased with the results too. I would say that your cross-platform developers made a miracle, as it has helped us to double our working efficiency. So many many thanks to you.", ""},
            {"Jouni Stam", "CTO at Yonoton", "", "The company made a great first impression with the business analyst who gathered requirements, measured the scope, and asked about our other needs. The project manager and other team members kept us informed about the business app's schedule and progress and made sure that everything was going according to our expectations. Andersen stands out where it comes to communication and planning.", START_WITH + "/our-projects/app-for-ordering-tickets-and-meal-during-matches"},
            {"Vasili Shamshur", "Senior Manager at IHS Markit", "", "Andersen has done an outstanding job to complete the project on time. The multitude of issues that the analytical system and management platform development throw at them has been handled professionally and efficiently. We definitely enjoy cooperation with this company and will continue to work with it in the future.", START_WITH + "/our-projects/software-platforms-for-engineers"},
            {"Heloïse Pinette", "Public relations expert at BNP Paribas", "", "Experts from Andersen showed incredible dedication and creativity while helping us meet this challenge. We discussed what was expected from the product with Business Analysts, and the result didn’t disappoint us: the solution includes all the necessary modules and functionality to cope with banking regulatory documents analysis effectively.", START_WITH + "/our-projects/solution-for-legislation-changes-monitoring"},
            {"Jeffrey Reyes", "Head of Testing at 3D4Medical Limited", "", "We have just started our relationship with Andersen, and they have proven to be a professional and effective organization. To date, my needs have been in the area of our healthcare consulting app's Quality Assurance. Projects were organized quickly, delivered successfully, and to a high standard. Working with a remote contractor, communication is key, and this Andersen excels in. I would highly recommend Andersen as a supplier of a quality product that meets specifications and is always ready on time.", ""}
    };
    private final int artsQuantity = TEXT_ARTICLES.length;
    private final Boolean buttonSlick = true;
}
