package com.andersenlab.autotests.site.page.industries.telecom.blocks;

import com.andersenlab.autotests.site.page.services.customsoftware.blocks.customerreviews.CustomerReviewsData;
import lombok.Getter;

@Getter
public class CustomerReviewsDataTelecom implements CustomerReviewsData {
    private final String[][] TEXT_ARTICLES = new String[][]{
            {"Roxana Porada", "Founder & VP Products at PXL Vision", "", "The best thing about Andersen’s services is the full transparency of processes. We always knew what’s going on with our business app and didn’t need to worry much about this project status, so it gives us the opportunity to focus on our business.", START_WITH + "/our-projects/verifeye"},
            {"Anna Sinyakova", "Procurement manager at Nexign", "", "Andersen quickly and seamlessly integrated all changes into the existed architecture. Providing confident and experienced assistance, the team implemented upgrades to our accommodating software that has reduced the testing time of new products and increased the speed of implementing new services.", START_WITH + "/our-projects/solution-for-software-testing"},
            {"Basil Stepanov", "Chief Technology Officer at Smart Choice Communications", "", "Andersen produced clean code and impressive deliverables cost-efficiently to support a competitive business advantage. All employees speak English very well. The design and development team works on our security platform development very organized and with modern project management methods. As a customer, we had a full overview of our project all the time.", ""},
            {"Peter Ford", "Director IT Development at AireSpring", "", "Andersen's self-sufficient project managers, their trustworthiness, and reliability make this company a strong partner. The team is flexible, adapting schedules to support effective collaboration and streamline product launches. Andersen delivered a user-friendly and simple to edit site which features make internal data tracking easier.", ""},
            {"Jessica Bourne", "Chief of Staff Team at AT&T", "", "Developers from Andersen are brilliant in their expertise. Great communication skills, reporting various challenges ahead of time. Andersen’s commitment to our information system development project allowed us to consult changes and track the progress on a regular basis. Given the complexity of the project, we're very happy with their output thus far.", ""},
            {"Alex Davenport", "CEO", "", "Andersen did a great job by establishing a Call Center we need to support our multimedia startup and improving its processes according to our requirements. It allowed us to concentrate the maximum of our resources on the development process without wasting time on services support.", ""},
            {"Jane Mitchell", "Product manager", "", "As our product came to the CIS market we faced the need to support our new customers from that area. We decided to work with Andersen and fully delegated them our support function for the CIS-based customers. Their specialists provided us the level of support services that we needed, so we’re happy with the customer satisfaction level and regular service improvements we see.", ""},
            {"Maksim Shulman", "CEO", "", "I am happy with the cooperation with Andersen which resulted in a much more professional level of IT services than the ones we had before. We’ve delegated Andersen all scope of IT support for our startup team that we need to develop our product. Our team is distributed and located in different parts of the world and that requires a 24/7 schedule, flexible approach, and understanding of different cultures. But Andersen's processes and quality of work are good enough to deal with those requirements and we even got some valuable outcomes we didn’t expect like the recommendations for the improvement of our internal processes. I recommend Andersen as a valuable and trusted vendor of outsourcing IT services.", ""},
            {"Neil Cohen", "COO", "", "We selected Andersen as our outsourced IT support partner looking for the cost optimization and improvement of our internal services. During our cooperation, the Andersen team has proven themselves as IT experts who know best practices in the support area and can implement them. With their attitude and continual improvement approach we got even more than expected, so I recommend Andersen as a great IT support outsourcing partner.", ""},
            {"Dmitry Guralnik", "Program manager", "", "Andersen's QA team has proven to be a very professional automated testing partner. The onboarding process was fast enough to get started quickly. The Andersen QA team proposes improvements to the development process and technical solutions. Recommended for cooperation.", ""}
    };
    private final int artsQuantity = TEXT_ARTICLES.length;
    private final Boolean buttonSlick = true;
}
